### ISSUE TITLE
Cython not declared as a dependency in setup.py

### ISSUE THREAD

**Issue by jbaiter** [gbishop/cython-hidapi#6]
Currently, an installation from Pip will fail because hidapi does not declare 'Cython' in its requirements.

```
$ pip install hidapi                                                                                                                                                      
Downloading/unpacking hidapi
  Downloading hidapi-0.7.0-1.tar.gz
  Running setup.py egg_info for package hidapi
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/jojo/.envs/spreads/build/hidapi/setup.py", line 9, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/jojo/.envs/spreads/build/hidapi/setup.py", line 9, in <module>

    from Cython.Distutils import build_ext

ImportError: No module named Cython.Distutils

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/jojo/.envs/spreads/build/hidapi
Storing complete log in /home/jojo/.pip/pip.log
```

**Comment by gordon-to** [comment]
Can also result in this error

``````
Installed /Users/ag/projects/csc490-arm/cython-hidapi/.eggs/Cython-0.23.4-py2.7-macosx-10.10-x86_64.egg
/Users/ag/virtualenvs/csc490-arm/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.7.99-8' to '0.7.99.post8'
  normalized_version,
running build
running build_ext
building 'hid' extension
error: unknown file type '.pxd' (from 'chid.pxd')```
``````
